import Nav from "./(components)/nav";
import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gr"><Nav />
       <div className="m-2">{children}</div>
      </body>
    </html>
  );
}
